server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_geo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
    username: root
    password: root
  jpa:
    #    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true



